#!/bin/bash

# original docker build command
echo "overwriting docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME ."

cat "cuda_tags.txt" | while read CUDA_TAG
do
        IMAGE_TAG="${DOCKER_REPO}:${CUDA_TAG}"
        echo "docker build --no-cache -f $DOCKERFILE_PATH --build-arg CUDA_BUILD_TAG=${CUDA_TAG} -t ${IMAGE_TAG} ."
        docker build --no-cache -f "$DOCKERFILE_PATH" --build-arg CUDA_BUILD_TAG="${CUDA_TAG}" -t "${IMAGE_TAG}" .
done
