#!/bin/bash

# original docker build command
echo "overwriting docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME ."

cat "cuda_versions.txt" | while read CUDA_VERSION
do
        if [ -z "$DOCKER_TAG" ]; then
            IMAGE_TAG="${DOCKER_REPO}:${CUDA_VERSION}"
        else
            IMAGE_TAG="${DOCKER_REPO}:${CUDA_VERSION}-${DOCKER_TAG}"
        fi
        echo "docker build -f $DOCKERFILE_PATH --build-arg CUDA_VERSION=${CUDA_VERSION} -t ${IMAGE_TAG} ."
        docker build -f "$DOCKERFILE_PATH" --build-arg CUDA_VERSION="${CUDA_VERSION}" -t "${IMAGE_TAG}" .
done
