#!/bin/bash

# original docker push command
cat "cuda_tags.txt" | while read CUDA_TAG
do
    IMAGE_TAG="nvidia/cuda:${CUDA_TAG}"
    echo "docker pull ${IMAGE_TAG}"
    docker pull ${IMAGE_TAG}

    IMAGE_TAG="${DOCKER_REPO}:${CUDA_TAG}"
    echo "docker pull ${IMAGE_TAG}"
    docker pull ${IMAGE_TAG}
done

exit 0
