#!/bin/bash

# original docker push command
echo "overwriting docker push $IMAGE_NAME"

cat "cuda_versions.txt" | while read CUDA_VERSION
do
    if [ -z "$DOCKER_TAG" ]; then
        IMAGE_TAG="${DOCKER_REPO}:${CUDA_VERSION}"
    else
        IMAGE_TAG="${DOCKER_REPO}:${CUDA_VERSION}-${DOCKER_TAG}"
    fi

    echo "docker pull ${IMAGE_TAG}"
    docker pull ${IMAGE_TAG}
done
