#!/bin/bash

# original docker push command
echo "overwriting docker push $IMAGE_NAME"

cat "cuda_tags.txt" | while read CUDA_TAG
do
    IMAGE_TAG="${DOCKER_REPO}:${CUDA_TAG}"
    echo "docker push ${IMAGE_TAG}"
    docker push ${IMAGE_TAG}
done
